"""Idempotent crontab installer with managed-block markers.

The watchdog cron line is wrapped in:

    # BEGIN claude_task_runner
    * * * * * /home/bill/github/claude_task_runner/src/claude_task_runner/cron/watchdog.sh
    # END claude_task_runner

The installer NEVER touches anything outside those markers — re-running
``install`` replaces the block in place; ``uninstall`` removes only the
block. ``crontab -l`` is backed up to
``~/.claude_task_runner/crontab.backup.<ts>`` before any change.

This module is the **plumbing**: it builds the new crontab text and
shells out to ``crontab(1)``. The interactive y/N confirmation lives in
the CLI layer (:mod:`cli.install_cmd`) so this module stays testable
without TTY interaction.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from claude_task_runner.clock import Clock

BEGIN_MARKER = "# BEGIN claude_task_runner"
END_MARKER = "# END claude_task_runner"
BLOCK_RE = re.compile(
    rf"^[ \t]*{re.escape(BEGIN_MARKER)}\b.*?\n(?:.*\n)*?[ \t]*{re.escape(END_MARKER)}\b.*?\n?",
    re.MULTILINE,
)
"""Match an existing managed block (entire ``BEGIN`` line through
``END`` line, inclusive) so we can replace or remove it cleanly."""


class CrontabError(RuntimeError):
    """Failure to read or write the crontab via ``crontab(1)``."""


@dataclass(frozen=True)
class InstallPlan:
    """The proposed change to the crontab. Generated by :func:`build_plan`
    and rendered to the operator for confirmation before
    :func:`apply_plan` actually writes it.

    Attributes
    ----------
    existing_text
        The crontab as ``crontab -l`` reports it now (empty string
        when the user has no crontab yet).
    new_text
        The proposed new crontab text.
    diff_lines
        A unified-style preview ``+ `` / ``- `` markers for the lines
        that will change. Suitable for printing.
    block_existed
        Whether a managed block already existed in the existing
        crontab — useful so the CLI can say "replacing existing block"
        vs "adding new block".
    """

    existing_text: str
    new_text: str
    diff_lines: list[str]
    block_existed: bool


def crontab_l(crontab_executable: str = "crontab") -> str:
    """Return the current crontab as text. Empty string if none.

    Differentiates "no crontab" (returns "") from a real failure
    (raises). ``crontab -l`` exits non-zero on missing crontab on most
    systems, with a recognizable stderr.
    """
    if shutil.which(crontab_executable) is None:
        raise CrontabError(f"{crontab_executable!r} not found on PATH")
    proc = subprocess.run(
        [crontab_executable, "-l"],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode == 0:
        return proc.stdout
    stderr = (proc.stderr or "").lower()
    if "no crontab" in stderr or proc.returncode == 1:
        return ""
    raise CrontabError(f"crontab -l failed with code {proc.returncode}: {proc.stderr.strip()}")


def build_block(watchdog_path: Path, schedule: str = "* * * * *") -> str:
    """Render the managed block for ``watchdog_path``.

    Default schedule is every minute; operators can pass a less
    frequent cadence (``"*/5 * * * *"``) when systemd isn't available
    and CPU is precious.
    """
    return f"{BEGIN_MARKER}\n{schedule} {watchdog_path}\n{END_MARKER}\n"


def replace_block(existing: str, new_block: str) -> tuple[str, bool]:
    """Return ``(new_crontab_text, block_existed)``.

    If a block already exists, replace it in place. Otherwise append.
    Existing non-managed lines are preserved verbatim. The returned
    text always ends with a newline.
    """
    if BLOCK_RE.search(existing):
        replaced = BLOCK_RE.sub(new_block, existing, count=1)
        return _ensure_trailing_newline(replaced), True
    base = existing if not existing or existing.endswith("\n") else existing + "\n"
    if base and not base.endswith("\n\n"):
        # Separate from prior content with a blank line for readability.
        base = base + "\n"
    return _ensure_trailing_newline(base + new_block), False


def remove_block(existing: str) -> tuple[str, bool]:
    """Return ``(new_crontab_text, block_existed)``.

    Strips the managed block from ``existing``. Lines outside the block
    are preserved verbatim.
    """
    if not BLOCK_RE.search(existing):
        return existing, False
    cleaned = BLOCK_RE.sub("", existing, count=1)
    # Collapse any leftover blank lines created by the removal.
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return _ensure_trailing_newline(cleaned).rstrip("\n") + ("\n" if cleaned.strip() else ""), True


def _ensure_trailing_newline(text: str) -> str:
    if not text:
        return ""
    return text if text.endswith("\n") else text + "\n"


def _diff_lines(before: str, after: str) -> list[str]:
    """Tiny line-by-line diff for confirmation display.

    Not a real ``diff`` — just ``- `` for removed lines and ``+ `` for
    added ones, in order. Sufficient for the operator to eyeball the
    change before confirming.
    """
    before_lines = before.splitlines()
    after_lines = after.splitlines()
    out: list[str] = []
    # We deliberately keep this dumb: most installs add or remove a
    # 3-line block, not a full crontab. A real diff library would be
    # overkill.
    before_set = set(before_lines)
    after_set = set(after_lines)
    for line in before_lines:
        if line not in after_set:
            out.append(f"- {line}")
    for line in after_lines:
        if line not in before_set:
            out.append(f"+ {line}")
    return out


def build_install_plan(
    *,
    watchdog_path: Path,
    schedule: str = "* * * * *",
    crontab_executable: str = "crontab",
) -> InstallPlan:
    """Plan an install: read current crontab, compute new text, diff."""
    existing = crontab_l(crontab_executable)
    new_block = build_block(watchdog_path, schedule)
    new_text, block_existed = replace_block(existing, new_block)
    return InstallPlan(
        existing_text=existing,
        new_text=new_text,
        diff_lines=_diff_lines(existing, new_text),
        block_existed=block_existed,
    )


def build_uninstall_plan(
    *,
    crontab_executable: str = "crontab",
) -> InstallPlan:
    """Plan an uninstall: read current crontab, strip block, diff."""
    existing = crontab_l(crontab_executable)
    new_text, block_existed = remove_block(existing)
    return InstallPlan(
        existing_text=existing,
        new_text=new_text,
        diff_lines=_diff_lines(existing, new_text),
        block_existed=block_existed,
    )


def backup_crontab(text: str, *, clock: Clock, dest_dir: Path | None = None) -> Path:
    """Write ``text`` to ``~/.claude_task_runner/crontab.backup.<ts>`` and
    return the path. Caller invokes this BEFORE applying the plan."""
    base = dest_dir if dest_dir is not None else Path.home() / ".claude_task_runner"
    base.mkdir(parents=True, exist_ok=True)
    stamp = clock.now().strftime("%Y%m%dT%H%M%SZ")
    path = base / f"crontab.backup.{stamp}"
    path.write_text(text)
    return path


def apply_plan(
    plan: InstallPlan,
    *,
    crontab_executable: str = "crontab",
) -> None:
    """Write ``plan.new_text`` to the user's crontab.

    Uses ``crontab -`` (read from stdin) which is the supported way to
    replace a crontab atomically from a script.
    """
    if shutil.which(crontab_executable) is None:
        raise CrontabError(f"{crontab_executable!r} not found on PATH")
    proc = subprocess.run(
        [crontab_executable, "-"],
        input=plan.new_text,
        text=True,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        raise CrontabError(f"crontab - failed with code {proc.returncode}: {proc.stderr.strip()}")
