"""YAML task scaffolding — generates new task files with sensible defaults."""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

from claude_runner.config import CONFIG_FILENAME, Settings
from claude_runner.defaults import Effort

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(text: str, *, max_len: int = 40) -> str:
    s = _SLUG_RE.sub("-", text.lower()).strip("-")
    if not s:
        s = "task"
    return s[:max_len].rstrip("-")


def next_id(todo_dir: Path, *, width: int = 3) -> str:
    existing: set[int] = set()
    for pat in ("*.yaml", "*.yml"):
        for path in todo_dir.glob(pat):
            stem = path.stem
            m = re.match(r"^(\d+)(?:[-_].*)?$", stem)
            if m:
                existing.add(int(m.group(1)))
    n = 1
    while n in existing:
        n += 1
    return f"{n:0{width}d}"


def render_task_yaml(
    *,
    task_id: str,
    title: str,
    prompt: str,
    working_dir: str,
    effort: Effort,
    model: str,
    allowed_tools: list[str],
    depends_on: list[str] | None = None,
) -> str:
    """Render a fully-populated task YAML string (valid for the loader)."""
    deps = depends_on or []
    tools_inline = ", ".join(allowed_tools)
    deps_inline = ", ".join(repr(d) for d in deps)
    indented_prompt = textwrap.indent(prompt.rstrip() + "\n", "  ")
    return (
        f"# {task_id} — {title}\n"
        f"id: {task_id}\n"
        f"title: {title}\n"
        f"prompt: |\n"
        f"{indented_prompt}"
        f"working_dir: {working_dir}\n"
        f"model: {model}\n"
        f"effort: {effort.value}\n"
        f"allowed_tools: [{tools_inline}]\n"
        f"max_turns: null           # null = derive from effort\n"
        f"estimated_input_tokens: null  # null = derive from effort\n"
        f"depends_on: [{deps_inline}]\n"
        f"priority: normal\n"
    )


def write_new_task(
    *,
    title: str,
    todo_dir: Path,
    settings: Settings,
    prompt: str | None = None,
    working_dir: Path | None = None,
    effort: Effort | None = None,
    model: str | None = None,
    depends_on: list[str] | None = None,
) -> Path:
    todo_dir.mkdir(parents=True, exist_ok=True)
    task_id = next_id(todo_dir)
    slug = slugify(title)
    filename = f"{task_id}-{slug}.yaml" if slug else f"{task_id}.yaml"
    path = todo_dir / filename
    body = render_task_yaml(
        task_id=task_id,
        title=title,
        prompt=prompt or f"TODO: describe what {title!r} should do.",
        working_dir=str(working_dir or Path.cwd()),
        effort=effort or settings.default_effort,
        model=model or settings.default_model,
        allowed_tools=list(settings.default_allowed_tools),
        depends_on=depends_on or [],
    )
    path.write_text(body, encoding="utf-8")
    return path


# ---- `init` scaffolding --------------------------------------------------

SAMPLE_CONFIG = """# claude_runner.toml — generated by `claude_runner init`

regime = "pro_max"            # pro_max | api
plan = "max5"                 # pro | max5 | max20 | team | custom
budget_source = "ccusage"     # ccusage | context | api_headers | static
backend = "asyncio"           # asyncio | subprocess

max_concurrency = 8
min_utilization = 0.80        # aim to use >=80% of every 5-hour window
weekly_guard = 0.90           # keep weekly usage <90% until the last day
refresh_interval_s = 30

max_consecutive_failures = 3
failure_rate_threshold = 0.5
failure_rolling_window = 10
failure_rate_min_samples = 4

default_effort = "medium"
default_model = "claude-opus-4-7"
default_allowed_tools = ["Read", "Edit", "Bash", "Grep", "Glob"]

discovery_cache_ttl_s = 60
"""

SAMPLE_TASK_TITLE = "Example — say hello"
SAMPLE_TASK_PROMPT = (
    "Write the word 'hello' to hello.txt in the working directory. Only the Write tool is needed."
)


def init_project(project_dir: Path, *, settings: Settings | None = None) -> dict[str, Path]:
    """Scaffold project_dir/ with config + example task + .gitignore entry."""
    if settings is None:
        settings = Settings()
    project_dir.mkdir(parents=True, exist_ok=True)
    todo_dir = project_dir / settings.todo_subdir
    todo_dir.mkdir(parents=True, exist_ok=True)

    config_path = project_dir / CONFIG_FILENAME
    if not config_path.exists():
        config_path.write_text(SAMPLE_CONFIG, encoding="utf-8")

    example_path = write_new_task(
        title=SAMPLE_TASK_TITLE,
        todo_dir=todo_dir,
        settings=settings,
        prompt=SAMPLE_TASK_PROMPT,
        working_dir=project_dir,
        effort=Effort.LOW,
    )

    gitignore = project_dir / ".gitignore"
    marker = f"{settings.state_subdir}/"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    if marker not in existing:
        new_contents = existing
        if new_contents and not new_contents.endswith("\n"):
            new_contents += "\n"
        new_contents += f"# claude_runner machine-written state\n{marker}\n"
        gitignore.write_text(new_contents, encoding="utf-8")

    return {
        "project_dir": project_dir,
        "todo_dir": todo_dir,
        "config": config_path,
        "example_task": example_path,
        "gitignore": gitignore,
    }
